---
openapi: 3.1.0
info:
  title: Budget Buddy API
  version: v1
paths:
  "/create-account":
    post:
      summary: Creates an unverified account. Sends a verification email to the provided
        email address.
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: unverified account has been created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string
              required:
              - email
              - password
              - passwordConfirm
            examples:
              '0':
                summary: Creates an unverified account. Sends a verification email
                  to the provided email address.
                value:
                  email: example01@email.com
                  password: 123qwe123
                  passwordConfirm: 123qwe123
  "/verify-account":
    post:
      summary: Verifies an account. The `key` is contained in the link that was sent
        to the user's email during account creation
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: account has been verified
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: The `key` is contained in the link that was sent to
                    the user's email during account creation
              required:
              - key
  "/login":
    post:
      summary: Logs in to an existing, verified account.
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user has been logged in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
            examples:
              '0':
                summary: Logs in to an existing, verified account.
                value:
                  email: example01@email.com
                  password: 123qwe123
  "/logout":
    post:
      summary: Logs out the current session. Include the `global_logout` attribute
        and pass any value to logout of all sessions, otherwise don't include it in
        the request body.
      tags:
      - Authentication
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '200':
          description: user has been logged out
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                global_logout:
                  type: string
                  description: Include this attribute and pass any value to logout
                    of all sessions, otherwise don't include it in the request body.
  "/verify-account-resend":
    post:
      summary: Resends account verification email. Note that there is a 5-minute delay
        between resends.
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: email verification has been resent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/categories":
    post:
      summary: Creates a new category
      tags:
      - Categories
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '201':
          description: category created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Category"
        '422':
          description: failed to create category
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      name:
                      - can't be blank
              schema:
                "$ref": "#/components/schemas/ResourceCreationError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateCategoryParams"
            examples:
              example:
                summary: Creates a new category
                value:
                  name: Transportation
                  categoryType: expense
    get:
      summary: Gets all categories associated to the logged in user
      tags:
      - Categories
      security:
      - bearer_auth: []
      parameters:
      - name: category_type
        in: query
        description: This is type of category to query. It can be `income` or `expense`.
          The request will return all the categories for the logged in user if this
          is not specified or its value is null.
        schema:
          type: string
      responses:
        '200':
          description: categories returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Category"
  "/categories/{id}":
    get:
      summary: Gets the details of a category
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: category returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Category"
        '404':
          description: category not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
    put:
      summary: Updates a category
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: category updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Category"
        '404':
          description: category not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateCategoryParams"
    delete:
      summary: deletes a category
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '204':
          description: category deleted
        '404':
          description: category not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
  "/expenses":
    post:
      summary: Creates a new expense transaction
      tags:
      - Expenses
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '201':
          description: expense transaction created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ExpenseTransaction"
        '422':
          description: expense transaction creation failed
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      category_id:
                      - can't be blank
              schema:
                "$ref": "#/components/schemas/ResourceCreationError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateExpenseParams"
            examples:
              example:
                summary: Creates a new expense transaction
                value:
                  financialAccountId: 1
                  categoryId: 1
                  description: Food
                  amount: 190.0
                  date: '2023-12-18T04:09:53.000Z'
    get:
      summary: Gets all expense transactions associated to the logged in user
      tags:
      - Expenses
      security:
      - bearer_auth: []
      responses:
        '200':
          description: expense transactions returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ExpenseTransaction"
  "/expenses/{id}":
    get:
      summary: Gets the details of an expense transaction
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: expense transaction returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ExpenseTransaction"
        '404':
          description: expense transaction not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
    put:
      summary: Updates an expense transaction
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: expense transaction updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ExpenseTransaction"
        '404':
          description: expense transaction not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateExpenseParams"
    delete:
      summary: deletes a expense
      tags:
      - Expenses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '204':
          description: expense transaction deleted
        '404':
          description: expense transaction not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
  "/financial_accounts":
    post:
      summary: Creates a new financial account
      tags:
      - Financial Accounts
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '201':
          description: financial account created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FinancialAccount"
        '422':
          description: failed to create financial account
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      name:
                      - can't be blank
              schema:
                "$ref": "#/components/schemas/ResourceCreationError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateFinancialAccountParams"
            examples:
              example:
                summary: Creates a new financial account
                value:
                  name: Cash
                  amount: 30.0
                  description: Cash on hand
    get:
      summary: Gets all financial accounts associated to the logged in user
      tags:
      - Financial Accounts
      security:
      - bearer_auth: []
      responses:
        '200':
          description: financial accounts returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/FinancialAccount"
  "/financial_accounts/{id}":
    get:
      summary: Gets the details of a financial account
      tags:
      - Financial Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: financial account returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FinancialAccount"
        '404':
          description: financial account not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
    put:
      summary: Updates a financial account
      tags:
      - Financial Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: financial account updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/FinancialAccount"
        '404':
          description: financial account not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateFinancialAccountParams"
    delete:
      summary: deletes a financial account
      tags:
      - Financial Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '204':
          description: financial account deleted
        '404':
          description: financial account not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
  "/incomes":
    post:
      summary: Creates a new income transaction
      tags:
      - Incomes
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '201':
          description: income transaction created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeTransaction"
        '422':
          description: income transaction creation failed
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      category_id:
                      - can't be blank
              schema:
                "$ref": "#/components/schemas/ResourceCreationError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateIncomeParams"
            examples:
              example:
                summary: Creates a new income transaction
                value:
                  financialAccountId: 1
                  categoryId: 1
                  description: Salar
                  amount: 190.0
                  date: '2023-12-18T04:09:53.000Z'
    get:
      summary: Gets all income transactions associated to the logged in user
      tags:
      - Incomes
      security:
      - bearer_auth: []
      responses:
        '200':
          description: income transactions returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/IncomeTransaction"
  "/incomes/{id}":
    get:
      summary: Gets the details of an income transaction
      tags:
      - Incomes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: income transaction returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeTransaction"
        '404':
          description: income transaction not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
    put:
      summary: Updates an income transaction
      tags:
      - Incomes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: income transaction updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/IncomeTransaction"
        '404':
          description: income transaction not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateIncomeParams"
    delete:
      summary: deletes a income
      tags:
      - Incomes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '204':
          description: income transaction deleted
        '404':
          description: income transaction not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
  "/current-account":
    get:
      summary: Retrieves the currently logged account
      tags:
      - Session
      security:
      - bearer_auth: []
      responses:
        '200':
          description: success
  "/transactions":
    get:
      summary: Gets all transactions associated with the currently logged user
      tags:
      - Transactions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Transaction"
  "/transactions/{id}":
    delete:
      summary: Deletes an income, expense, or transfer transaction
      tags:
      - Transactions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '204':
          description: transaction successfully deleted
        '404':
          description: transaction not found
  "/transfers":
    post:
      summary: Creates a new transfer transaction
      tags:
      - Transfers
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '201':
          description: transfer transaction created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransferTransaction"
        '422':
          description: failed to create transfer transaction
          content:
            application/json:
              examples:
                example:
                  value:
                    errors:
                      fromFinancialAccountId:
                      - can't be blank
              schema:
                "$ref": "#/components/schemas/ResourceCreationError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateTransferParams"
            examples:
              example:
                summary: Creates a new transfer transaction
                value:
                  fromFinancialAccountId: 1
                  toFinancialAccountId: 2
                  description: ATM Withdrawal
                  amount: 190.0
                  date: '2023-12-18T04:09:53.000Z'
    get:
      summary: Gets all transfer transactions associated to the logged in user
      tags:
      - Transfers
      security:
      - bearer_auth: []
      responses:
        '200':
          description: transfer transactions returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/TransferTransaction"
  "/transfers/{id}":
    get:
      summary: Gets the details of a transfer transaction
      tags:
      - Transfers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: transfer transaction returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransferTransaction"
        '404':
          description: transfer not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
    put:
      summary: Updates an transfer transaction
      tags:
      - Transfers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '200':
          description: transfer updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransferTransaction"
        '404':
          description: transfer not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateTransferParams"
    delete:
      summary: deletes a transfer
      tags:
      - Transfers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - bearer_auth: []
      responses:
        '204':
          description: transfer deleted
        '404':
          description: transfer not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResourceNotFoundError"
  "/change-login":
    post:
      summary: Requests change of account email. Sends confirmation email to the new
        email.
      tags:
      - Account Management
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '200':
          description: change email link has been sent to the new email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The new email.
                password:
                  type: string
              required:
              - email
              - password
  "/verify-login-change":
    post:
      summary: Changes the account email. The `key` is contained in the link that
        was sent to the new email when the change of email was requested.
      tags:
      - Account Management
      parameters: []
      responses:
        '200':
          description: account email has been changed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  description: The `key` is contained in the link that was sent to
                    the new email when the change of email was requested.
              required:
              - key
  "/change-password":
    post:
      summary: Changes account password. `password` here is the old password.
      tags:
      - Account Management
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '200':
          description: password has been changed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: The old password
                newPassword:
                  type: string
                passwordConfirm:
                  type: string
              required:
              - password
              - newPassword
              - passwordConfirm
  "/reset-password-request":
    post:
      summary: Requests change of account password. Sends a password reset link to
        the current email.
      tags:
      - Account Management
      parameters: []
      responses:
        '200':
          description: password reset link has been sent to the email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/reset-password":
    post:
      summary: Changes the account password. The `key` is contained in the password
        reset link that was sent to the account's email.
      tags:
      - Account Management
      parameters: []
      responses:
        '200':
          description: password reset link has been sent to the email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                password-confirm:
                  type: string
                key:
                  type: string
                  description: The `key` is contained in the password reset link that
                    was sent to the account's email.
              required:
              - password
              - password-confirm
              - key
  "/close-account":
    post:
      summary: Closes the account. Note that there is not endpoint for reopening the
        account.
      tags:
      - Account Management
      parameters: []
      security:
      - bearer_auth: []
      responses:
        '200':
          description: account has been closed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
              required:
              - password
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    TransactionType:
      type: string
      enum:
      - income
      - expense
      - transfer
    CategoryType:
      type: string
      enum:
      - income
      - expense
    ResourceCreationError:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      required:
      - errors
    ResourceNotFoundError:
      type: object
      properties:
        error:
          type: string
    CreateFinancialAccountParams:
      type: object
      properties:
        name:
          type: string
        initialAmount:
          type: number
          format: double
        description:
          type: string
          nullable: true
      required:
      - name
      - initialAmount
    UpdateFinancialAccountParams:
      type: object
      properties:
        name:
          type: string
        initialAmount:
          type: number
          format: double
        description:
          type: string
    FinancialAccount:
      type: object
      properties:
        name:
          type: string
        initialAmount:
          type: number
          format: double
        currentBalance:
          type: number
          format: double
        description:
          type: string
          nullable: true
        id:
          type: integer
    CreateCategoryParams:
      type: object
      properties:
        categoryType:
          "$ref": "#/components/schemas/CategoryType"
        name:
          type: string
      required:
      - name
      - categoryType
    UpdateCategoryParams:
      type: object
      properties:
        categoryType:
          "$ref": "#/components/schemas/CategoryType"
        name:
          type: string
    Category:
      type: object
      properties:
        categoryType:
          "$ref": "#/components/schemas/CategoryType"
        name:
          type: string
        id:
          type: integer
    ExpenseTransaction:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        transactionType:
          type: string
        financialAccount:
          "$ref": "#/components/schemas/FinancialAccount"
        category:
          "$ref": "#/components/schemas/Category"
        id:
          type: integer
    IncomeTransaction:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        transactionType:
          type: string
        financialAccount:
          "$ref": "#/components/schemas/FinancialAccount"
        category:
          "$ref": "#/components/schemas/Category"
        id:
          type: integer
    TransferTransaction:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        transactionType:
          type: string
        fromFinancialAccount:
          "$ref": "#/components/schemas/FinancialAccount"
        toFinancialAccount:
          "$ref": "#/components/schemas/FinancialAccount"
        id:
          type: integer
    Transaction:
      oneOf:
      - "$ref": "#/components/schemas/ExpenseTransaction"
      - "$ref": "#/components/schemas/IncomeTransaction"
      - "$ref": "#/components/schemas/TransferTransaction"
      discriminator:
        propertyName: transactionType
        mapping:
          expense: "#/components/schemas/ExpenseTransaction"
          income: "#/components/schemas/IncomeTransaction"
          transfer: "#/components/schemas/TransferTransaction"
    CreateExpenseParams:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        financialAccountId:
          type: integer
        categoryId:
          type: integer
      required:
      - financialAccountId
      - categoryId
      - amount
      - date
    UpdateExpenseParams:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        financialAccountId:
          type: integer
        categoryId:
          type: integer
    CreateIncomeParams:
      allOf:
      - "$ref": "#/components/schemas/CreateExpenseParams"
    UpdateIncomeParams:
      allOf:
      - "$ref": "#/components/schemas/UpdateExpenseParams"
    CreateTransferParams:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        fromFinancialAccountId:
          type: integer
        toFinancialAccountId:
          type: integer
      required:
      - fromFinancialAccountId
      - toFinancialAccountId
      - categoryId
      - amount
      - date
    UpdateTransferParams:
      type: object
      properties:
        date:
          type: string
        amount:
          type: number
          format: double
        description:
          type: string
          nullable: true
        fromFinancialAccountId:
          type: integer
        toFinancialAccountId:
          type: integer
servers:
- url: "{url}"
  variables:
    url:
      default: https://budget-buddy-backend.fly.dev
